version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest-browsers
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm run test:single-run
            - run:
                name: build
                command: npm run build
            - deploy:
                name: firebase
                command: firebase deploy --token=$FIREBASE_TOKEN